language: cpp
os: linux
dist: xenial
services: docker

addons:
  apt:
    packages:
      - libboost-system-dev
      - libmysqlclient-dev
      - socat

script:
  - mkdir build && cd build && cmake ..
  - cmake --build . --parallel 6
  - ctest --output-on-failure
