language: cpp
os: linux
dist: xenial
services: docker

addons:
  apt:
    packages:
      - libboost-system-dev
      - libmysqlclient-dev
      - socat

script:
  - mkdir build && cd build && cmake .. -DTEST_EXTENDED_ENABLED=ON
  - cmake --build . --parallel 6
  - cmake --build . --parallel 6 --target test_odr
  - ctest --output-on-failure

before_deploy: |
  # GitHub releaser script (https://github.com/lindell/github-release-cli)
  # used because standard github-release deploy module doesn't support specifying release message from ENV
  curl https://github.com/lindell/github-release-cli/releases/download/1.3.0/github-releaser-travis --fail --location --output github-releaser && chmod +x github-releaser \
    || (echo "Failed to download github-releaser script" && return 1)
  pip install gitchangelog pystache
  ## get changes from commit messages since last tag
  CURRENT_TAG=$(git describe --tags --abbrev=0 HEAD)
  PREV_TAG=$(git describe --tags --abbrev=0 ${CURRENT_TAG}~1)
  export BODY=$(gitchangelog ${PREV_TAG}..${CURRENT_TAG})

deploy:
  provider: script
  script: ./github-releaser -draft -verbose
  skip_cleanup: true
  on:
    tags: true
