language: cpp
os: linux
dist: xenial
services: docker

addons:
  apt:
    packages:
      - libboost-system-dev
      - libmysqlclient-dev
      - socat

script:
  - mkdir build && cd build && cmake .. -DTEST_EXTENDED_ENABLED=ON
  - cmake --build . --parallel 6
  - cmake --build . --parallel 6 --target test_odr
  - ctest --output-on-failure

before_deploy: |
  # GitHub releaser script (https://github.com/lindell/github-release-cli)
  # used because standard github-release deploy module doesn't support specifying release message from ENV
  curl https://github.com/lindell/github-release-cli/releases/download/1.3.0/github-releaser-travis --fail --location --output github-releaser && chmod +x github-releaser \
    || (echo "Failed to download github-releaser script" && return 1)
  ## get changes from debian's changelog
  export BODY=`dpkg-parsechangelog --file debian/changelog --show-field Changes | grep --invert-match --extended-regexp '^$|^libsuperiormysqlpp |^  \[ '`

deploy:
  provider: script
  script: ./github-releaser -draft -verbose
  skip_cleanup: true
  on:
    tags: true
